# Generated by Django 2.2 on 2019-11-10 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['id_estado'],
            },
        ),
        migrations.CreateModel(
            name='Estado_pedido',
            fields=[
                ('id_estado_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estado.Estado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido')),
            ],
            options={
                'verbose_name': 'Estado_pedido',
                'verbose_name_plural': 'Estados_pedido',
                'ordering': ['id_estado_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Estado_lote',
            fields=[
                ('id_estado_lote', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Detalle')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estado.Estado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido')),
            ],
            options={
                'verbose_name': 'Estado_lote',
                'verbose_name_plural': 'Estados_lote',
                'ordering': ['id_estado_lote'],
            },
        ),
    ]
