# Generated by Django 2.2 on 2019-09-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_pedido',
            fields=[
                ('id_estado_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado.Estado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_lote',
            fields=[
                ('id_estado_lote', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Detalle')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido')),
            ],
        ),
    ]
