# Generated by Django 2.2 on 2020-01-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_pedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido'),
        ),
        migrations.AddField(
            model_name='estado_lote',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Detalle'),
        ),
        migrations.AddField(
            model_name='estado_lote',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estado.Estado'),
        ),
        migrations.AddField(
            model_name='estado_lote',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido'),
        ),
    ]
