# Generated by Django 2.2 on 2019-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
