# Generated by Django 2.2 on 2019-11-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0002_auto_20191110_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_pedido',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
