# Generated by Django 2.2 on 2019-11-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0003_auto_20191114_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_pedido',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estado.Estado'),
        ),
        migrations.AlterField(
            model_name='estado_pedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido'),
        ),
    ]
