# Generated by Django 2.2 on 2019-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('tiempo_prod_lote', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('entrega', models.DecimalField(decimal_places=3, max_digits=10)),
                ('seña', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estado', models.CharField(max_length=100)),
                ('prioridad_entrega', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
