# Generated by Django 2.2 on 2020-01-14 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0001_initial'),
        ('pedido', '0001_initial'),
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faltante',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Material'),
        ),
        migrations.AddField(
            model_name='faltante',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido'),
        ),
        migrations.AddField(
            model_name='faltante',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prenda.Prenda'),
        ),
        migrations.AddField(
            model_name='faltante',
            name='tipo_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Tipo_material'),
        ),
        migrations.AddField(
            model_name='entregas',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Prenda'),
        ),
    ]
