# Generated by Django 2.2 on 2019-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedido',
            name='prioridad_entrega',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridad_entrega',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
    ]
