# Generated by Django 2.2 on 2019-09-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='activo',
        ),
    ]
