# Generated by Django 2.2 on 2019-10-02 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20191002_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entrega',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='seña',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator('0.00')]),
        ),
    ]
