# Generated by Django 2.2 on 2019-11-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20191114_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
