# Generated by Django 2.2 on 2020-01-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20200113_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
