# Generated by Django 2.2 on 2019-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20191115_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedido',
            name='puntaje',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='puntaje',
            field=models.CharField(blank=True, default=2, max_length=50, null=True),
        ),
    ]
