# Generated by Django 2.2 on 2020-01-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20200121_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpedido',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='puntaje',
        ),
    ]
