# Generated by Django 2.2 on 2020-01-06 04:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20191121_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido')),
            ],
        ),
    ]
