# Generated by Django 2.2 on 2020-01-29 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200122_2153'),
        ('pedido', '0005_entregas_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_envio',
            fields=[
                ('id_detalle_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('domicilio', models.CharField(max_length=500)),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.Pedido')),
            ],
        ),
    ]
