# Generated by Django 2.2 on 2019-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20191014_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='tiempo_prod_lote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
