# Generated by Django 2.2 on 2019-10-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_auto_20191014_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='tiempo_prod_lote',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
