# Generated by Django 2.2 on 2020-01-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_detalle_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_envio',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
