# Generated by Django 2.2 on 2019-09-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_prenda',
            fields=[
                ('id_tipo_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('talle', models.IntegerField()),
                ('tiempo_prod_prenda', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('tipo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenda.Tipo_prenda')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenda.Componente')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Material')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenda.Prenda')),
            ],
        ),
    ]
