# Generated by Django 2.2 on 2019-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('talle', models.IntegerField()),
                ('tiempo_prod_prenda', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_prenda',
            fields=[
                ('id_tipo_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
