# Generated by Django 2.2 on 2020-01-14 01:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medida', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Unidad_medida')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medida',
                'ordering': ['id_medida'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_prenda',
            fields=[
                ('id_tipo_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('medida', models.ManyToManyField(to='prenda.Medida')),
            ],
            options={
                'verbose_name': 'Tipo de Prenda',
                'verbose_name_plural': 'Tipos de Prenda',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('talle', models.PositiveIntegerField()),
                ('tiempo_prod_prenda', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prendas')),
                ('tipo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prenda.Tipo_prenda')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prenda',
                'ordering': ['id_prenda'],
            },
        ),
        migrations.CreateModel(
            name='Medida_prenda',
            fields=[
                ('id_medida_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Medida')),
                ('prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Prenda')),
            ],
            options={
                'verbose_name': 'Medida_prenda',
                'verbose_name_plural': 'Medida_prenda',
                'ordering': ['id_medida_prenda'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidadxdetalle', models.PositiveIntegerField(default=0)),
                ('disponibilidad', models.CharField(default='', max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Material')),
                ('prenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Prenda')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingrediente',
                'ordering': ['id_ingrediente'],
            },
        ),
    ]
