# Generated by Django 2.2 on 2019-10-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='imagen',
            field=models.FileField(null=True, upload_to='prendas'),
        ),
    ]
