# Generated by Django 2.2 on 2019-11-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
