# Generated by Django 2.2 on 2019-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='prendas'),
        ),
    ]
