# Generated by Django 2.2 on 2019-09-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_prenda',
            name='componente',
            field=models.ManyToManyField(to='prenda.Componente'),
        ),
    ]
