# Generated by Django 2.2 on 2019-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='nombre',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
