# Generated by Django 2.2 on 2019-11-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0002_auto_20191109_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_prenda',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
