# Generated by Django 2.2 on 2019-10-02 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0002_auto_20191002_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
