# Generated by Django 2.2 on 2020-01-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0002_remove_ingrediente_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='disponibilidad',
            field=models.CharField(default='', max_length=50),
        ),
    ]
