# Generated by Django 2.2 on 2019-10-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0003_auto_20191002_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Componente'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.Material'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Prenda'),
        ),
    ]
