# Generated by Django 2.2 on 2020-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0003_ingrediente_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
