# Generated by Django 2.2 on 2019-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0003_auto_20191023_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.FileField(default='None', null=True, upload_to='prendas'),
        ),
    ]
