# Generated by Django 2.2 on 2019-11-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20191110_0957'),
        ('prenda', '0003_auto_20191109_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medida', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Unidad_medida')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medida',
                'ordering': ['id_medida'],
            },
        ),
        migrations.RemoveField(
            model_name='tipo_prenda',
            name='componente',
        ),
        migrations.DeleteModel(
            name='Componente',
        ),
        migrations.AddField(
            model_name='tipo_prenda',
            name='medida',
            field=models.ManyToManyField(to='prenda.Medida'),
        ),
    ]
