# Generated by Django 2.2 on 2019-10-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0004_auto_20191016_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='talle',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='tiempo_prod_prenda',
            field=models.PositiveIntegerField(),
        ),
    ]
