# Generated by Django 2.2 on 2019-10-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0004_auto_20191023_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.FileField(null=True, upload_to='prendas'),
        ),
    ]
