# Generated by Django 2.2 on 2019-11-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0004_auto_20191115_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida_prenda',
            fields=[
                ('id_medida_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prenda.Medida')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prenda.Prenda')),
            ],
            options={
                'verbose_name': 'Medida_prenda',
                'verbose_name_plural': 'Medida_prenda',
                'ordering': ['id_medida_prenda'],
            },
        ),
    ]
