# Generated by Django 2.2 on 2019-10-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0005_auto_20191016_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='componente',
        ),
    ]
