# Generated by Django 2.2 on 2019-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0005_medida_prenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida_prenda',
            name='valor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
