# Generated by Django 2.2 on 2019-10-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0005_auto_20191023_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='prendas'),
        ),
    ]
