# Generated by Django 2.2 on 2019-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0006_auto_20191023_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.ImageField(null=True, upload_to='prendas'),
        ),
    ]
