# Generated by Django 2.2 on 2019-11-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0006_medida_prenda_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida_prenda',
            name='medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Medida'),
        ),
        migrations.AlterField(
            model_name='medida_prenda',
            name='prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prenda.Prenda'),
        ),
        migrations.AlterField(
            model_name='medida_prenda',
            name='valor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
