# Generated by Django 2.2 on 2019-12-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0007_auto_20191117_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='cantidadxdetalle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='disponibilidad',
            field=models.CharField(default='', max_length=50),
        ),
    ]
