# Generated by Django 2.2 on 2020-01-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0009_faltante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faltante',
        ),
    ]
