# Generated by Django 2.2 on 2019-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
