# Generated by Django 2.2 on 2019-09-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='material',
            field=models.ManyToManyField(to='material.Material'),
        ),
    ]
