# Generated by Django 2.2 on 2019-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
