# Generated by Django 2.2 on 2019-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_material',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad_medida',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
