# Generated by Django 2.2 on 2020-01-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(default='#ffffff', max_length=50),
        ),
    ]
