# Generated by Django 2.2 on 2019-09-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20190922_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad_medida',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
