# Generated by Django 2.2 on 2020-01-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_faltante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faltante',
        ),
    ]
