# Generated by Django 2.2 on 2020-01-25 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_material_disponibilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='disponibilidad',
        ),
    ]
