# Generated by Django 2.2 on 2020-01-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('logo', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionMensaje',
            fields=[
                ('id_configuracion_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('en_espera', models.TextField(default='En espera')),
                ('en_produccion', models.TextField(default='En producción')),
                ('cancelado', models.TextField(default='Cancelado')),
                ('finalizado', models.TextField(default='Finalizado')),
                ('entregado', models.TextField(default='Entregado')),
                ('entrega', models.TextField(default='Entrega')),
            ],
        ),
    ]
