# Generated by Django 2.2 on 2019-12-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
