# Generated by Django 2.2 on 2019-12-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20191204_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMensaje',
            fields=[
                ('id_configuracion_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('en_espera', models.TextField()),
                ('en_produccion', models.TextField()),
                ('cancelado', models.TextField()),
                ('finalizado', models.TextField()),
                ('entregado', models.TextField()),
            ],
        ),
    ]
