# Generated by Django 2.2 on 2019-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_configuracionmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmensaje',
            name='entrega',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='cancelado',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='en_espera',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='en_produccion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='entregado',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='finalizado',
            field=models.TextField(default=''),
        ),
    ]
