# Generated by Django 2.2 on 2019-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20191211_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='cancelado',
            field=models.TextField(default='Cancelado'),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='en_espera',
            field=models.TextField(default='En espera'),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='en_produccion',
            field=models.TextField(default='En producción'),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='entrega',
            field=models.TextField(default='Entrega'),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='entregado',
            field=models.TextField(default='Entregado'),
        ),
        migrations.AlterField(
            model_name='configuracionmensaje',
            name='finalizado',
            field=models.TextField(default='Finalizado'),
        ),
    ]
