# Generated by Django 2.2 on 2019-11-10 00:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='DNI')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefonos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correos')),
                ('domicilio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Domicilios')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('dni', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)], verbose_name='DNI')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefonos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correos')),
                ('domicilio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Domicilios')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
