# Generated by Django 2.2 on 2019-10-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.PositiveIntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
    ]
