# Generated by Django 2.2 on 2019-12-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20191110_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='reputación',
            field=models.IntegerField(default=100, verbose_name='reputacion'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='reputación',
            field=models.IntegerField(default=100, verbose_name='reputacion'),
        ),
    ]
