# Generated by Django 2.2 on 2019-12-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20191223_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='reputación',
            new_name='reputacion',
        ),
        migrations.RenameField(
            model_name='historicalcliente',
            old_name='reputación',
            new_name='reputacion',
        ),
    ]
